fix: provide subprocess stderr to user on error
Previously, only the following would be printed. Now, stderr is
printed too, which makes debugging on the user side possible.

subprocess.CalledProcessError: Command '['bitcoin-cli', 'getchaintips']' returned non-zero exit status 1.